#!/usr/bin/env ruby

require 'rubygems'

# The lower version of xcodeproj is not available because the API has changed.
gem "xcodeproj", ">=0.14.0"
require 'xcodeproj'

if ARGV[1] != "iPhone"
  exit
end

projpath = ARGV[0] + "/Unity-iPhone.xcodeproj"

proj = Xcodeproj::Project.open(projpath)

proj.targets.each do |target|
  next unless target.name == "Unity-iPhone"

  # Add Frameworks
  target.add_system_framework("MessageUI")
  target.add_system_framework("StoreKit")
  target.add_system_framework("AdSupport")
  target.add_system_framework("CoreTelephony")

  # Add Other Linker Flags
   target.build_settings("Debug")["OTHER_LDFLAGS"] << "-ObjC"
  target.build_settings("Release")["OTHER_LDFLAGS"] << "-ObjC"
end

# Change framework path type to 'Relative to SDK'
proj["Frameworks"]["iOS"].files.each do |file|
  file.path.gsub!(/.*(System\/.*\.framework)$/, '\1')
  file.source_tree.gsub!(/DEVELOPER_DIR/, "SDKROOT")
end

proj.save(projpath)
